### ISSUE TITLE
Include Vagrantfile?

### ISSUE THREAD

**Issue by dhafley** [DylanAlloy/UnicornBreakfast#2]
For portability, it would be great to have the Vagrantfile listed in the directory.  Vagrant commands are usually the entry point for the end user instead of a wrapper script, in my opinion.

Having the Vagrantfile as it's own entity would also allow for greater flexibility in host OS (run from Mac, CentOS, or Ubuntu) and cleaner addition of boxes in the guest OS scope.

**Comment by DylanAlloy** [comment]
Totally understandable. In a conversation with Steve, we talked about how using python would be okay, but after thinking about it more and considering environments the implementation makes more sense to assume different priorities centered around vagrant.
